### ISSUE TITLE
editor를 사용하고 싶어요.

### ISSUE THREAD

**Issue by athilog** [nhn/toast-ui.react-grid#3]
```js
const columns = [
  {
    title: "Name",
    name: "name",
    editor: "text"
  }
];

export default () => {
  return (
    <Grid
      data={data}
      columns={columns}
      rowHeight={25}
      bodyHeight={1000}
      virtualScrolling={true}
      heightResizable={true}
      rowHeaders={["rowNum"]}
    />
  );
});
```

이렇게 시도 해봤는데 editor는 작동하지 않네요.
아직 지원하지 않는건가요?

**Comment by athilog** [comment]
예제소스를 보고나서 
 editOptions: {type: 'text'}
이렇게 하면 된다는걸 알았는데
react에서 쓰는 다른 api는 어디있는건가요?
https://nhn.github.io/tui.grid/latest/Grid
이건 javascript api 인듯하고, 아니면 혹시 이전버젼 api 인가요?

**Comment by jung-han** [comment]
@ToKimSeoYeon 안녕하세요. 
어제 grid 4.0 버전이 배포되어 latest 버전 api가 아닌 이전버전의 API 문서를 확인 해주셔야 될 것 같습니다. 

* https://nhn.github.io/tui.grid/3.8.0/ 

API는 기존 그리드 API를 그대로 사용할 수 있으며 인스턴스를 그대로 가져오는 방식으로 사용할 수 있습니다.
* https://github.com/nhn/toast-ui.react-grid#instance-methods

4.0 버전에서 변경된 API들은 현재 리액트 래퍼에는 적용이 되어있지 않은 상태이며 조만간 변경할 예정입니다. 감사합니다.

**Comment by athilog** [comment]
빠른고 좋은설명 감사해요^^

**Comment by ToKimSeoYeon** [comment]
추가로 하나만 더 여쭤 보고싶은게 있는데
데이터 수정후 Grid에선 어떻게 Data를 가져오나요?
